const CONTENT = [
  {
    week: 1,
    date: "Jan 13 - Jan 19",
    title: "Week 1: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 1-20",
  },
  {
    week: 2,
    date: "Jan 20 - Jan 26",
    title: "Week 2: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 21-40",
  },
  {
    week: 3,
    date: "Jan 27 - Feb 2",
    title: "Week 3: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 41-60",
  },
  {
    week: 4,
    date: "Feb 3 - Feb 9",
    title: "Week 4: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 61-80",
  },
  {
    week: 5,
    date: "Feb 10 - Feb 16",
    title: "Week 5: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 81-100",
  },
  {
    week: 6,
    date: "Feb 17 - Feb 23",
    title: "Week 6: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 101-120",
  },
  {
    week: 7,
    date: "Feb 24 - Mar 2",
    title: "Week 7: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 121-140",
  },
  {
    week: 8,
    date: "Mar 3 - Mar 9",
    title: "Week 8: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 141-160",
  },
  {
    week: 9,
    date: "Mar 10 - Mar 16",
    title: "Week 9: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 161-180",
  },
  {
    week: 10,
    date: "Mar 17 - Mar 23",
    title: "Week 10: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 181-200",
  },
  {
    week: 11,
    date: "Mar 24 - Mar 30",
    title: "Week 11: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 201-220",
  },
  {
    week: 12,
    date: "Mar 31 - Apr 6",
    title: "Week 12: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 221-240",
  },
  {
    week: 13,
    date: "Apr 7 - Apr 13",
    title: "Week 13: Placeholder Title",
    video: require("../assets/videos/placeholder.mp4"),
    thumbnail: require("../assets/images/thumbnail.jpg"),
    reading: "pp. 241-260",
  },
];

export default CONTENT;
